<!DOCTYPE html>
<html lang="en" ng-app="taskConfirmationApp">
  <head>
    <meta charset="utf-8" />
    <title><?= APP_TITLE ?> | <?= $this->title ?></title>
    <meta name="viewport"
        content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=yes">
    <?= $this->headMeta() ?>
    <link rel="icon" href="/favicon.png" type="image/png">
    <link rel="shortcut icon" href="/favicon.ico">
    <?= $this->headLink()?>
    <link href="/css/vreasy/fuelux.css" rel="stylesheet" />
    <link type="text/css" rel='stylesheet' href='/css/vreasy/vreasy.css'>
    <script type="text/javascript" src="/bower_components/angular/angular.min.js"></script>
    <script type="text/javascript" src="/bower_components/underscore/underscore-min.js"></script>
    <script type="text/javascript" src="/bower_components/angular-ui-router/release/angular-ui-router.min.js"></script>
    <script type="text/javascript" src="/bower_components/angular-resource/angular-resource.min.js"></script>
    <script type="text/javascript" src="/taskConfirmationApp/app.js"></script>
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar"
            data-toggle="collapse"
            data-target=".nav-collapse">
                <span class="icon-bar"></span>
          </a>
          <a class="brand"
            href="/">
                <img src="/vreasy-logotype-dark.png" title="<?= APP_TITLE ?>">
          </a>
          <div class="nav-collapse collapse">
            <ul class="nav">
                <li>
                    <a href="/tasks">Tasks</a>
                </li>
            </ul>
            <ul class="nav pull-right">
                <li>
                    <a href="#">Property Manager</a>
                </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="container"
        id="vreasy-main-container"
        style="position: relative;">
            <?= $this->layout()->content; ?>
    </div>
    <hr>
    <div class="container">
      <footer>
        <p class="ar copyright pull-right">
            <small>
              &copy; <?= APP_TITLE ?> &trade; <?= date('Y') ?> version <?= APP_VERSION ?> <?= APPLICATION_ENV == 'production' ? '' : APPLICATION_ENV ?>
            </small>
        </p>
      </footer>
   </div>
  </body>
</html>
